### ISSUE TITLE
Missing volume stats

### ISSUE THREAD

**Issue by yoshz** [hetznercloud/csi-driver#50]
I would like to see volume stats in Grafana/Prometheus but it is currently not implemented:
https://github.com/hetznercloud/csi-driver/blob/ee4eb5241e6e7a4ebaf55e6363077b7cd2dd3381/src/driver/node.go#L192

Is it possible to implement this?

I am running Kubernetes 1.15 and it also ends up in the runtime error, but that is related to a bug in Kubelet.
```
Sep 07 12:05:22 k8s-01 kubelet[1587]: E0907 12:05:22.976215    1587 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Sep 07 12:05:22 k8s-01 kubelet[1587]: goroutine 2589 [running]:
Sep 07 12:05:22 k8s-01 kubelet[1587]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3995be0, 0x7565dd0)
Sep 07 12:05:22 k8s-01 kubelet[1587]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
Sep 07 12:05:22 k8s-01 kubelet[1587]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Sep 07 12:05:22 k8s-01 kubelet[1587]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
Sep 07 12:05:22 k8s-01 kubelet[1587]: panic(0x3995be0, 0x7565dd0)
Sep 07 12:05:22 k8s-01 kubelet[1587]:         /usr/local/go/src/runtime/panic.go:522 +0x1b5
Sep 07 12:05:22 k8s-01 kubelet[1587]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).parsePodVolumeStats(0xc000df8000, 0xc0012d37a0, 0x2c, 0xc000aade80, 0x0, 0xc0012d37a0, 0x2c, 0x0, 0x0, 0x0, ...)
Sep 07 12:05:22 k8s-01 kubelet[1587]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:143 +0xf5
Sep 07 12:05:22 k8s-01 kubelet[1587]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).calcAndStoreStats(0xc000df8000)
Sep 07 12:05:22 k8s-01 kubelet[1587]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:125 +0x753
Sep 07 12:05:22 k8s-01 kubelet[1587]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1.1()
Sep 07 12:05:22 k8s-01 kubelet[1587]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:65 +0x2a
Sep 07 12:05:22 k8s-01 kubelet[1587]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00134b9b0)
Sep 07 12:05:22 k8s-01 kubelet[1587]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
Sep 07 12:05:22 k8s-01 kubelet[1587]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00134b9b0, 0xdf8475800, 0x3ff0000000000000, 0xc000a75d01, 0xc000c2ea80)
Sep 07 12:05:22 k8s-01 kubelet[1587]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
Sep 07 12:05:22 k8s-01 kubelet[1587]: created by k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1
Sep 07 12:05:22 k8s-01 kubelet[1587]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:64 +0x9d
```

**Comment by LKaemmerling** [comment]
We have officially released v1.2.0 of the driver with support for volume stats:
https://github.com/hetznercloud/csi-driver/blob/master/CHANGES.md#v120
