### ISSUE TITLE
PVC remains pending for provided example

### ISSUE THREAD

**Issue by thewilli** [hetznercloud/csi-driver#55]
I used the provided example from the README on a Kubernetes 1.15.3 cluster with nodes in Falkenstein. The PVC stays pending and no actual volume is created. I've followed the installation guidelines and the `hcloud-csi-controller` and `hcloud-csi-node` pods are up and running.

Relevant logs:

*kubelet* (restarting kubelet didn't make the error go away)
```plain
goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/csi.hetzner.cloud/csi.sock" failed. No retries permitted until 2019-09-15 12:45:19.70614928 +0200 CEST m=+500.438830540 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/csi.hetzner.cloud/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
```

*csi-provisioner*
```plain
W0915 10:38:33.285927       1 deprecatedflags.go:53] Warning: option provisioner="csi.hetzner.cloud" is deprecated and has no effect
I0915 10:38:33.286242       1 feature_gate.go:226] feature gates: &{map[Topology:true]}
I0915 10:38:33.290270       1 csi-provisioner.go:98] Version: v1.2.1-0-g971feacb
I0915 10:38:33.290337       1 csi-provisioner.go:112] Building kube configs for running in cluster...
I0915 10:38:36.401565       1 connection.go:151] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
I0915 10:38:36.403549       1 connection.go:261] Probing CSI driver for readiness
I0915 10:38:36.403614       1 connection.go:180] GRPC call: /csi.v1.Identity/Probe
I0915 10:38:36.403624       1 connection.go:181] GRPC request: {}
I0915 10:38:36.407791       1 connection.go:183] GRPC response: {"ready":{"value":true}}
I0915 10:38:36.409259       1 connection.go:184] GRPC error: <nil>
I0915 10:38:36.409284       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I0915 10:38:36.409294       1 connection.go:181] GRPC request: {}
I0915 10:38:36.412205       1 connection.go:183] GRPC response: {"name":"csi.hetzner.cloud","vendor_version":"1.1.5"}
I0915 10:38:36.413428       1 connection.go:184] GRPC error: <nil>
I0915 10:38:36.413473       1 csi-provisioner.go:152] Detected CSI driver csi.hetzner.cloud
I0915 10:38:36.413535       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I0915 10:38:36.413727       1 connection.go:181] GRPC request: {}
I0915 10:38:36.417803       1 connection.go:183] GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}},{"Type":{"Service":{"type":2}}}]}
I0915 10:38:36.460950       1 connection.go:184] GRPC error: <nil>
I0915 10:38:36.460972       1 connection.go:180] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0915 10:38:36.460981       1 connection.go:181] GRPC request: {}
I0915 10:38:36.464584       1 connection.go:183] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]}
I0915 10:38:36.468865       1 connection.go:184] GRPC error: <nil>
I0915 10:38:36.469972       1 controller.go:621] Using saving PVs to API server in background
I0915 10:38:36.470352       1 controller.go:769] Starting provisioner controller csi.hetzner.cloud_hcloud-csi-controller-0_f90ff697-d7a4-11e9-ad08-0620f8431eee!
I0915 10:38:36.470712       1 volume_store.go:90] Starting save volume queue
I0915 10:38:36.470916       1 reflector.go:123] Starting reflector *v1.PersistentVolume (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:803
I0915 10:38:36.470966       1 reflector.go:161] Listing and watching *v1.PersistentVolume from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:803
I0915 10:38:36.470963       1 reflector.go:123] Starting reflector *v1.StorageClass (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:806
I0915 10:38:36.470993       1 reflector.go:161] Listing and watching *v1.StorageClass from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:806
I0915 10:38:36.471304       1 reflector.go:123] Starting reflector *v1.PersistentVolumeClaim (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:800
I0915 10:38:36.471338       1 reflector.go:161] Listing and watching *v1.PersistentVolumeClaim from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:800
I0915 10:38:36.570641       1 shared_informer.go:123] caches populated
# the next 2 lines are repeated with different IDs, removed to keep this small
I0915 10:38:36.571073       1 controller.go:979] Final error received, removing PVC 1d96eb1e-a6e6-493e-be67-aa02769f5594 from claims in progress
I0915 10:38:36.571293       1 controller.go:902] Provisioning succeeded, removing PVC 1d96eb1e-a6e6-493e-be67-aa02769f5594 from claims in progress
I0915 10:45:47.507851       1 reflector.go:370] sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:803: Watch close - *v1.PersistentVolume total 0 items received
I0915 10:46:55.502540       1 reflector.go:370] sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:800: Watch close - *v1.PersistentVolumeClaim total 1 items received
I0915 10:48:18.501216       1 reflector.go:370] sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:806: Watch close - *v1.StorageClass total 0 items received
I0915 10:52:54.515268       1 reflector.go:370] sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:803: Watch close - *v1.PersistentVolume total 0 items received 
```

*csi-node-driver-registrar*
```plain
I0915 10:38:31.793335       1 main.go:110] Version: v1.1.0-0-g80a94421
I0915 10:38:31.793474       1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
I0915 10:38:31.793522       1 connection.go:151] Connecting to unix:///csi/csi.sock
I0915 10:38:35.035721       1 main.go:127] Calling CSI driver to discover driver name
I0915 10:38:35.035807       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I0915 10:38:35.035825       1 connection.go:181] GRPC request: {}
I0915 10:38:35.044697       1 connection.go:183] GRPC response: {"name":"csi.hetzner.cloud","vendor_version":"1.1.5"}
I0915 10:38:35.046671       1 connection.go:184] GRPC error: <nil>
I0915 10:38:35.046691       1 main.go:137] CSI driver name: "csi.hetzner.cloud"
I0915 10:38:35.046828       1 node_register.go:54] Starting Registration Server at: /registration/csi.hetzner.cloud-reg.sock
I0915 10:38:35.047106       1 node_register.go:61] Registration Server started at: /registration/csi.hetzner.cloud-reg.sock
I0915 10:38:35.418927       1 main.go:77] Received GetInfo call: &InfoRequest{}
I0915 10:38:36.416927       1 main.go:77] Received GetInfo call: &InfoRequest{}
I0915 10:38:36.562893       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,} 
```

*hcloud-csi-driver*
```plain
level=debug ts=2019-09-15T10:38:33.588757102Z msg="getting instance id from metadata service"
level=debug ts=2019-09-15T10:38:33.590703152Z msg="fetching server"
level=info ts=2019-09-15T10:38:34.070134005Z msg="fetched server" server-name=<my-node-name>
level=debug ts=2019-09-15T10:38:35.043748134Z component=grpc-server msg="handling request" req=
level=debug ts=2019-09-15T10:38:35.043910982Z component=grpc-server msg="finished handling request"
```

**Comment by githubixx** [comment]
I have the same issue also with K8s 1.15.3:
```
Sep 18 22:37:44 worker01 kubelet[10769]: I0918 22:37:44.116876   10769 operation_generator.go:193] parsed scheme: ""
Sep 18 22:37:44 worker01 kubelet[10769]: I0918 22:37:44.116979   10769 operation_generator.go:193] scheme "" not registered, fallback to default scheme
Sep 18 22:37:44 worker01 kubelet[10769]: I0918 22:37:44.117081   10769 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{/var/lib/kubelet/plugins/csi.hetzner.cloud/csi.sock 0  <nil>}]
Sep 18 22:37:44 worker01 kubelet[10769]: I0918 22:37:44.117113   10769 clientconn.go:796] ClientConn switching balancer to "pick_first"
Sep 18 22:37:44 worker01 kubelet[10769]: I0918 22:37:44.117233   10769 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc001108280, CONNECTING
Sep 18 22:37:44 worker01 kubelet[10769]: I0918 22:37:44.118235   10769 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc001108280, READY
Sep 18 22:37:44 worker01 kubelet[10769]: E0918 22:37:44.119063   10769 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/csi.hetzner.cloud/csi.sock" failed. No retries permitted until 2019-09-18 22:39:46.119019122 +0200 CEST m=+602873.003627714 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/csi.hetzner.cloud/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
```
Funny enough I get the error on both of my worker nodes. While I was able to create a PVC in worker02 the PV wasn't created and the container that wanted to mount that PV stayed in `ContainerCreating` status.
On worker01 I was able to create PVC, PV and also start a pod with the volume. But I can't delete it via `kubectl delete pv pvc-...`. This command just doesn't return. Only after deleting the volume via Cloud UI and running the command again the status of the persistentVolume changed to `Terminating`. And after deleting the PVC the PV and PVC was finally gone.

I'm also getting this errors:

Sep 18 22:44:12 worker01 kubelet[10769]: I0918 22:44:12.354414   10769 clientconn.go:440] parsed scheme: ""
Sep 18 22:44:12 worker01 kubelet[10769]: I0918 22:44:12.354459   10769 clientconn.go:440] scheme "" not registered, fallback to default scheme
Sep 18 22:44:12 worker01 kubelet[10769]: I0918 22:44:12.354527   10769 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{/var/lib/kubelet/plugins/csi.hetzner.cloud/csi.sock 0  <nil>}]
Sep 18 22:44:12 worker01 kubelet[10769]: I0918 22:44:12.354542   10769 clientconn.go:796] ClientConn switching balancer to "pick_first"
Sep 18 22:44:12 worker01 kubelet[10769]: I0918 22:44:12.354593   10769 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc001109230, CONNECTING
Sep 18 22:44:12 worker01 kubelet[10769]: I0918 22:44:12.355036   10769 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc001109230, READY
Sep 18 22:44:12 worker01 kubelet[10769]: E0918 22:44:12.355974   10769 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Sep 18 22:44:12 worker01 kubelet[10769]: goroutine 1534 [running]:
Sep 18 22:44:12 worker01 kubelet[10769]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3995be0, 0x7565dd0)
Sep 18 22:44:12 worker01 kubelet[10769]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
Sep 18 22:44:12 worker01 kubelet[10769]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Sep 18 22:44:12 worker01 kubelet[10769]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
Sep 18 22:44:12 worker01 kubelet[10769]: panic(0x3995be0, 0x7565dd0)
Sep 18 22:44:12 worker01 kubelet[10769]:         /usr/local/go/src/runtime/panic.go:522 +0x1b5
Sep 18 22:44:12 worker01 kubelet[10769]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).parsePodVolumeStats(0xc0015dc500, 0xc000a7fbf4, 0x4, 0xc0011f7140, 0x0, 0xc000a7fbf4, 0x4, 0x0, 0x0, 0x0, ...)
Sep 18 22:44:12 worker01 kubelet[10769]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:143 +0xf5
Sep 18 22:44:12 worker01 kubelet[10769]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).calcAndStoreStats(0xc0015dc500)
Sep 18 22:44:12 worker01 kubelet[10769]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:125 +0x753
Sep 18 22:44:12 worker01 kubelet[10769]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1.1()
Sep 18 22:44:12 worker01 kubelet[10769]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:65 +0x2a
Sep 18 22:44:12 worker01 kubelet[10769]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0012e77f0)
Sep 18 22:44:12 worker01 kubelet[10769]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
Sep 18 22:44:12 worker01 kubelet[10769]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0012e77f0, 0xdf8475800, 0x3ff0000000000000, 0xc000c08d01, 0xc0011a98c0)
Sep 18 22:44:12 worker01 kubelet[10769]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
Sep 18 22:44:12 worker01 kubelet[10769]: created by k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1
Sep 18 22:44:12 worker01 kubelet[10769]:         /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:64 +0x9d

Also I'm using the recommended versions for K8s 1.15 for the CSI infrastructure (according to https://kubernetes-csi.github.io/docs/):
```
hcloud_csi_node_driver_registrar: "1.1.0"
hcloud_csi_attacher: "1.2.0"
hcloud_csi_provisioner: "1.3.0"
hcloud_csi_cluster_driver_registrar: "1.0.1"
hcloud_csi_driver: "1.1.4"
```

**Comment by githubixx** [comment]
Maybe one update: While I was still logged in to the Cloud UI trying to create a PVC + PV a message popped up that I need to shutdown the server in order to make volumes work for that server. A restart is not enough! Now I was also able to execute the example code and I also was able to delete the PV + PVC again.

I'm still getting the error
```
Sep 18 23:16:58 worker02 kubelet[1884]: I0918 23:16:58.630918    1884 operation_generator.go:193] parsed scheme: ""
Sep 18 23:16:58 worker02 kubelet[1884]: I0918 23:16:58.630996    1884 operation_generator.go:193] scheme "" not registered, fallback to default scheme
Sep 18 23:16:58 worker02 kubelet[1884]: I0918 23:16:58.631078    1884 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{/var/lib/kubelet/plugins/csi.hetzner.cloud/csi.sock 0  <nil>}]
Sep 18 23:16:58 worker02 kubelet[1884]: I0918 23:16:58.631110    1884 clientconn.go:796] ClientConn switching balancer to "pick_first"
Sep 18 23:16:58 worker02 kubelet[1884]: I0918 23:16:58.631188    1884 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc000e5fdf0, CONNECTING
Sep 18 23:16:58 worker02 kubelet[1884]: I0918 23:16:58.636341    1884 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc000e5fdf0, READY
Sep 18 23:16:58 worker02 kubelet[1884]: E0918 23:16:58.637263    1884 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/csi.hetzner.cloud/csi.sock" failed. No retries permitted until 2019-09-18 23:19:00.637236448 +0200 CEST m=+629.312569819 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/csi.hetzner.cloud/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
```
but I would assume that `failed to get plugin info using RPC GetInfo` with the result `code = Unimplemented` basically means that this is just a function that is not implemented yet but is not necessary for normal operations. But maybe I'm wrong here.

**Comment by alexanderkjeldaas** [comment]
Same on single-node microk8s install using the default Ubuntu snap.

**Comment by alexanderkjeldaas** [comment]
```
$ kubectl describe pod hcloud-csi-node-thdlp --namespace kube-system
...
  Normal   Scheduled    3m17s                default-scheduler                            Successfully assigned kube-system/hcloud-csi-node-thdlp to workstation-ubuntu-32gb-nbg1-dc3-1
  Warning  FailedMount  74s                  kubelet, workstation-ubuntu-32gb-nbg1-dc3-1  Unable to attach or mount volumes: unmounted volumes=[registration-dir], unattached volumes=[plugin-dir registration-dir hcloud-csi-token-w9jg8 kubelet-dir device-dir]: timed out waiting for the condition
  Warning  FailedMount  69s (x9 over 3m17s)  kubelet, workstation-ubuntu-32gb-nbg1-dc3-1  MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry/ is not a directory
```

Could https://github.com/rancher/rke/issues/1151 be related?

**Comment by ostretsov** [comment]
Same problem with "invalid memory address". It happens ~1000 times a day (`cat syslog.1 | grep "invalid memory address or nil pointer dereference" | wc -l`). Any updates on this?

Kubernetes server 1.15.3 with csi driver 1.1.5.

Extract from the log files with the error:
```
Jan  4 06:45:36 k8s-n02 kubelet[1246]: I0104 06:45:36.952905    1246 clientconn.go:440] parsed scheme: ""
Jan  4 06:45:36 k8s-n02 kubelet[1246]: I0104 06:45:36.953005    1246 clientconn.go:440] scheme "" not registered, fallback to default scheme
Jan  4 06:45:36 k8s-n02 kubelet[1246]: I0104 06:45:36.953135    1246 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{/var/lib/kubelet/plugins/csi.hetzner.cloud/csi.sock 0  <nil>}]
Jan  4 06:45:36 k8s-n02 kubelet[1246]: I0104 06:45:36.953174    1246 clientconn.go:796] ClientConn switching balancer to "pick_first"
Jan  4 06:45:36 k8s-n02 kubelet[1246]: I0104 06:45:36.953255    1246 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc000ec7420, CONNECTING
Jan  4 06:45:36 k8s-n02 kubelet[1246]: I0104 06:45:36.953540    1246 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc000ec7420, READY
Jan  4 06:45:36 k8s-n02 kubelet[1246]: E0104 06:45:36.956259    1246 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Jan  4 06:45:36 k8s-n02 kubelet[1246]: goroutine 3332 [running]:
Jan  4 06:45:36 k8s-n02 kubelet[1246]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3995be0, 0x7565dd0)
Jan  4 06:45:36 k8s-n02 kubelet[1246]: #011/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
Jan  4 06:45:36 k8s-n02 kubelet[1246]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Jan  4 06:45:36 k8s-n02 kubelet[1246]: #011/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
Jan  4 06:45:36 k8s-n02 kubelet[1246]: panic(0x3995be0, 0x7565dd0)
Jan  4 06:45:36 k8s-n02 kubelet[1246]: #011/usr/local/go/src/runtime/panic.go:522 +0x1b5
Jan  4 06:45:36 k8s-n02 kubelet[1246]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).parsePodVolumeStats(0xc0015c5720, 0xc000b92020, 0x13, 0xc001739fe0, 0x0, 0xc000b92020, 0x13, 0x0, 0x0, 0x0, ...)
Jan  4 06:45:36 k8s-n02 kubelet[1246]: #011/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:143 +0xf5
Jan  4 06:45:36 k8s-n02 kubelet[1246]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).calcAndStoreStats(0xc0015c5720)
Jan  4 06:45:36 k8s-n02 kubelet[1246]: #011/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:125 +0x753
Jan  4 06:45:36 k8s-n02 kubelet[1246]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1.1()
Jan  4 06:45:36 k8s-n02 kubelet[1246]: #011/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:65 +0x2a
Jan  4 06:45:36 k8s-n02 kubelet[1246]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000ec7c60)
Jan  4 06:45:36 k8s-n02 kubelet[1246]: #011/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
Jan  4 06:45:36 k8s-n02 kubelet[1246]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ec7c60, 0xdf8475800, 0x3ff0000000000000, 0xc000a7ad01, 0xc00178f500)
Jan  4 06:45:36 k8s-n02 kubelet[1246]: #011/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
Jan  4 06:45:36 k8s-n02 kubelet[1246]: created by k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1
Jan  4 06:45:36 k8s-n02 kubelet[1246]: #011/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:64 +0x9d
```

**Comment by ninja-** [comment]
I've had similar problems and the workaround was to kill deamonset pod of csi-driver.
I haven't noticed any go panics in specific, but mainly the message that it can't connect to csi driver unix socket...

**Comment by Berndinox** [comment]
i face this issue, any solutions?

**Comment by timbrd** [comment]
Same here. My cluster is running in Falkenstein too

**Comment by ninja-** [comment]
Try checking for crashed pods in kube-system namespace and delete them

**Comment by Berndinox** [comment]
there were some failed deployment, i removed all of them. all the volumes get removed on cloud side, also the pvc (the claim) gets removed just the pv is stuck on "deleting":

 kubectl get pv
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM
               STORAGECLASS     REASON   AGE
pvc-0187f059-21e2-49f8-85f0-e96ffd91a4df   10Gi       RWO            Delete           Terminating   wp-bernd/wp-bernd-wordpress        hcloud-volumes            19h
pvc-0531c6b3-3aaa-4bd1-ab94-a66e31732b15   10Gi       RWO            Delete           Terminating   wp-bernd/wp-bernd-wordpress        hcloud-volumes            17h
pvc-70b34e81-d92e-4719-89d2-b3ca3987777f   10Gi       RWO            Delete           Terminating   wp-bernd/data-wp-bernd-mariadb-0   hcloud-volumes            19h
```

kubectl get all -n=wp-bernd
`No resources found in wp-bernd namespace`

**Comment by LKaemmerling** [comment]
Could you please test the latest release (v1.3.2)? We fixed a bug with this release which may lead to the described problem.

**Comment by onpaws** [comment]
Seem to be having the same problem. Falkenstein, no dead pods, followed the steps in https://github.com/hetznercloud/csi-driver#getting-started
